# Generated by Django 4.0.4 on 2023-12-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_chat_id_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='git',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
