version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    volumes:
      - .:/pythonNikitka
      - /pythonNikitka/__pycache__
    environment:
      - TELEGRAM_TOKEN=6345593543:AAGur9qqX3CsEZAG7qOurL_gn3qZWIYwfY4
      - TELEGRAM_CHAT_ID=-4016136242
      - AUTHORIZED_CHAT_ID=621545666
    command: python manage.py bot
    depends_on:
      - db
