version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: bot
    volumes:
      - .:/pythonNikitka
      - /pythonNikitka/__pycache__
    env_file:
      - .env
    command: python manage.py bot  # Здесь задайте нужную команду для запуска бота
    depends_on:
      - db
