version: "3"

services:
  db:
    build: .
    container_name: app_container_name
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  app:
    build: .
    container_name: bot
    volumes:
      - .:/pythonNikitka
      - /pythonNikitka/__pycache__
    env_file:
      - .env
    command: python manage.py bot  # Здесь задайте нужную команду для запуска бота
    depends_on:
      - db
