version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= 457849da
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  pghero:
    image: ankane/pghero
    container_name: pghero
    network_mode: host
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://user:password@hostaddress:5432
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
volumes:
  db:
    driver: local