version: "3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./scripts/install-extensions.sql:/docker-entrypoint-initdb.d/install-extensions.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    volumes:
      - .:/pythonNikitka
      - /pythonNikitka/__pycache__
    env_file:
      - .env
    command: python manage.py bot  # Здесь задайте нужную команду для запуска бота
    depends_on:
      - db
