version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= 457849da
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
volumes:
  db:
    driver: local