version: "3.8"

services:
  app:  # This service is for the Django application
    build: .
    container_name: django_container
    volumes:
      - .:/app  # Mounts the project directory to /app in the container
      - sqlite_data:/app/db.sqlite3  # Mounts the named volume to where the SQLite database is expected
    command: python manage.py bot  # Runs your bot command
    ports:
      - "8000:8000"  # Expose ports if needed (e.g., for web interface)

volumes:
  sqlite_data:  # Declares the named volume for SQLite
